name: Pull Requests CI

on:
  push:
    branches:
      - master
      - 'release*'

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - run: bash ./gradlew test — stacktrace
