name: Pull Requests CI

on:
  pull_request:
  branches:
  - 'master'
  - 'release*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: set up JDK 1.8
    - uses: actions/setup-java@v3
      with:
        java-version: 1.8
        name: Unit tests
    - run: bash ./gradlew test — stacktrace
  build-and-generate-apk:
    - runs-on: ubuntu-latest
    steps:
    uses: actions/checkout@v4
      name: set up JDK 1.8
    uses: actions/setup-java@v3
      with:
        java-version: 1.8
        name: Unit tests
    name: Install NDK
    - run: echo “y” | sudo ${ANDROID_HOME}/tools/bin/sdkmanager — install “ndk;26.1.10909125”
    name: Build Debug 
    - run: ./gradlew assembleDebug
    name: Upload APK on Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: f1_app
        path: app/build/outputs/apk/debug/app-debug.apk
