name: Pull Requests CI

on:
  push:
    branches:
      - master
      - 'release*'

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - run: bash ./gradlew test --stacktrace
  build_and_generate_app:
    name: Building Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Debug
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v3
        with:
          name: f1_app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: '${{ secrets.FIREBASE_APP_ID }}'
          serviceCredentialsFileContent: '${{ secrets.CREDENTIAL_FILE_CONTENT }}'
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
